### PR TITLE
fix: respect `foldopen='undo'` (#18)

### LINKED ISSUE #18: Bug: `foldopen="undo"` is being ignored
by default, undoing things should open folds if undoing something in a folded location. (`:h foldopen`). With this plugin enabled, that is not the case

### PR DESCRIPTION
**Pull request by chrisgrieser**
fixes #18

### CODE REVIEW

File: lua/highlight-undo.lua [hunk 1]
```diff
@@ -109,6 +109,13 @@ function M.clear_highlights(bufnr)
   )
 end
 
+---makes highlight-undo respect `foldopen=undo` (#18)
+local function openFolsOnUndo()
```
Comment (tzachar) [inline lua/highlight-undo.lua]: Only issue is the small typo here.....

Comment (chrisgrieser) [reply lua/highlight-undo.lua]: fixed!

**Comment by tzachar** [comment]
10x :)
